# .github/workflows/keepalive.yml
name: Database Keepalive

on:
  schedule:
    - cron: '0 */5 * * *'  # Every 5 hours (more reliable than 5 days)
  workflow_dispatch:       # Allows manual triggers

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -s -X GET \
          "https://${{ vars.APP_URL }}/api/keepalive" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"